import { openSans, oswald, popins } from "@/fonts";
import Footer from "./Footer";
import Header from "./Header";
import "@/styles/globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-100">
      <body
        className={`${openSans.variable} ${oswald.variable} ${popins.variable} w-100 h-100 d-flex flex-column color-darkness-second`}
      >
        <Header />
        <main className="flex-grow-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
